### PR TITLE
Release 3.3.0

### PR DESCRIPTION
**Pull request by thiemowmde**
There is currently not much in this release, see https://github.com/wmde/WikibaseDataModelServices/compare/3.2.0...master. Please have a look at the open pull requests before tagging a release. I added some to the 3.3.0 milestone, but we may want to merge some more that are currently not in the milestone. Please talk to me if you are not sure.

Would be cool to release this today.

### CODE REVIEW

**Comment by filbertkm** [comment]
why are the changes to the fixtures part of this pull request?

**Comment by thiemowmde** [comment]
@filbertkm The date is fine, let's keep it.

The fixtures are updated to be compatible with DataModel 5. This does not break compatibility with version 4. The additional methods do nothing when you run the tests with DataModel 4.

**Comment by Benestar** [comment]
> @filbertkm The date is fine, let's keep it.

Do I have to understand that? /me confused.

**Comment by thiemowmde** [comment]
Refers to https://github.com/wmde/WikibaseDataModelServices/commit/6adb81dcaf222d2e6f1b26430b01406e21bdb648#commitcomment-16173107. I updated the date now.

**Pull request merged**
