### PR TITLE
Add RedirectResolvingEntityLookup, moved from Wikibase Lib

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Copy-paste, not changed to the code appart from the NS difference

### CODE REVIEW

**Comment by thiemowmde** [comment]
+1, looks good.

**Comment by addshore** [comment]
Per the discussion we just had on IRC this is going to end up throwing something

**Comment by JeroenDeDauw** [comment]
Well yeah sure. I did not change anything here compared to WB.git though. So I think its easiest to address this if we merge this class and then make a PR that adds an exception and documents it in all the docblocks.

**Comment by thiemowmde** [comment]
> I did not change anything here compared to WB.git though.

What do you mean? This copy misses the two `@throws StorageException` tags in question. They are not just comments but part of the contract of the class - something you taught me.

**Comment by JeroenDeDauw** [comment]
If I removed any such comments then I forgot they where there in the first place when I wrote that comment, I certainly can't remember them now.

**Comment by addshore** [comment]
These will be added back in with or after https://github.com/wmde/WikibaseDataModelServices/pull/42 before the next release

**Pull request merged**
