### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by Ladsgroup**
Dropping support for hhvm and diff 2.3

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
3.17

**Comment by mariushoch** [comment]
> 3.17

You mean 3.16 (last released is 3.15 AFAICT)? I'd also go for that, I don't think this needs a new major version.

**Comment by Ladsgroup** [comment]
> > 3.17
> 
> You mean 3.16 (last released is 3.15 AFAICT)? I'd also go for that, I don't think this needs a new major version.

Yeah, it should be 3.16 but isn't dropping php version a breaking change?

**Comment by jdforrester** [comment]
> > You mean 3.16 (last released is 3.15 AFAICT)? I'd also go for that, I don't think this needs a new major version.
> 
> Yeah, it should be 3.16 but isn't dropping php version a breaking change?

It is. We've done major versions in other libraries when dropping HHVM/PHP5.6/etc.

**Comment by jdforrester** [comment]
(Also, +"Fixes #225.")

**Pull request merged**
