### PR TITLE
3.1.0 release

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@filbertkm @thiemowmde @adrianheine

**Comment by filbertkm** [comment]
@JeroenDeDauw do want to tag the release?

**Comment by thiemowmde** [comment]
I double checked and found two mistakes in the release notes, see #86. With this fix the release can be done, in my opinion.

**Comment by JeroenDeDauw** [comment]
I've merged the corrections and tagged the release

**Pull request merged**
