### PR TITLE
Remove @group tags left in some of the moved tests

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by Benestar** [comment]
Since when do we avoid having `@group` tags in tests? I think some users might rely on the `--group` feature PHPUnit provides.

**Comment by JeroenDeDauw** [comment]
> Since when do we avoid having @group tags in tests?

About two years ago I guess. We discussed that internally on the list and in some meetings. Perhaps people are still doing this in some places in WB.git (because there we need to use the stupid MW test runner), though in our components we no longer have these.

**Comment by addshore** [comment]
+1
I don't use groups, even through the mediawiki test runner...

**Comment by mariushoch** [comment]
I'm not sure the MediaWiki test runner will pick these up, without `@group Wikibase`, which is especially bad for the build. Can you look at this @JanZerebecki?

**Comment by JeroenDeDauw** [comment]
@mariushoch these classes are not registered with the MediaWiki test runner to begin with. If you want to investigate if we should change that, fine, though out of scope here. We've been not using @group since forever for our components.

**Comment by Benestar** [comment]
So do I understand it right that those tags should also be removed from WikibaseDataModel?

**Comment by JeroenDeDauw** [comment]
I just checked and am surprised by the number of tags left there. Still, they are by far the exception rather than the rule.

**Pull request merged**
