### PR TITLE
Drop hhvm from travis because broken

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
All new PRs are red now:
* https://github.com/wmde/WikibaseDataModelServices/pull/205
* https://github.com/wmde/WikibaseDataModelServices/pull/204

### CODE REVIEW

**Comment by Ladsgroup** [comment]
WMF is still on hhvm, I suggest not dropping it until WMF has migrated to php7

**Comment by JeroenDeDauw** [comment]
It's either dropping this or fixing the issue. I think fixing the issue would be a waste of time. Don't let me stop you though. If you think you can justify spending time on it, by all means go for it.

**Comment by thiemowmde** [comment]
> […] because broken

What exactly is broken? What would be needed to fix it properly?

I had a brief look at the error messages in #205 and it seems the issue might as well be fixable by temporarily disabling/removing PHPMD.

**Comment by thiemowmde** [comment]
The PHPMD idea seems to work, see #207.

**Pull request closed without merging**
