### PR TITLE
Test with PHP 7.1 and 7.2 on Travis CI

### PR DESCRIPTION
**Pull request by manicki**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
```
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/src/Util/Getopt.php on line 38
PHP Stack trace:
PHP   1. {main}() /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/src/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_Command->handleArguments() /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/src/TextUI/Command.php:111
PHP   5. PHPUnit_Util_Getopt::getopt() /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/src/TextUI/Command.php:240
PHP   6. each() /home/travis/build/wmde/WikibaseDataModelServices/vendor/phpunit/phpunit/src/Util/Getopt.php:38
```

Used PHPUnit version is too ancient

**Comment by JeroenDeDauw** [comment]
Failing test:

```
1) Wikibase\DataModel\Services\Tests\Diff\StatementListPatcherTest::testPatchStatementList with data set #8 (Wikibase\DataModel\Statement\StatementList Object (...), Diff\DiffOp\Diff\Diff Object (...), Wikibase\DataModel\Statement\StatementList Object (...))
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
 Wikibase\DataModel\Statement\StatementList Object (
     'statements' => Array (
-        0 => Wikibase\DataModel\Statement\Statement Object (...)
+        1 => Wikibase\DataModel\Statement\Statement Object (...)
     )
 )
/home/travis/build/wmde/WikibaseDataModelServices/tests/unit/Diff/StatementListPatcherTest.php:106
```

**Comment by manicki** [comment]
OMG

**Comment by JeroenDeDauw** [comment]
Leszek you need to work on your communication skills. This is not acceptable. Let me show you how it is done:
1269259657_omg_cat

**Comment by manicki** [comment]
Troo. I cannot really hide I am too old for the internetz.

**Comment by thiemowmde** [comment]
If it's the PHPUnit version, why does the same at https://github.com/wmde/WikibaseDataModel/pull/772 work just fine with PHP 7.2?

**Comment by manicki** [comment]
@thiemowmde: The problem with the ancient PHPUnit version is also present in the other lib, although deprecation warning is ignored, so builds are green, e.g. https://travis-ci.org/wmde/WikibaseDataModel/jobs/329406633

There is an issue with the test here, which is impossible to ignore. Will have a look.

**Comment by JeroenDeDauw** [comment]
Superseded by https://github.com/wmde/WikibaseDataModelServices/pull/198

**Pull request closed without merging**
