### PR TITLE
Release 3.7

### PR DESCRIPTION
**Pull request by jakobw**
Some patches outside of this repo depend on `UnknownForeignRepositoryException` so it would be nice to have this released.

### CODE REVIEW

**Comment by manicki** [comment]
`PrefixMappingEntityIdParser` has been also added. I am not sure if want to explicitly mention it, or is it OK to only mentioned the factory class.

**Comment by jakobw** [comment]
Added it!

**Comment by JeroenDeDauw** [comment]
If the thing is package public, it should be mentioned. If it's package private, it should not be mentioned, though then its good to mention in the class doc that it is indeed package private (instead of having a since tag)

**Comment by manicki** [comment]
~~-1
Please note that per https://phabricator.wikimedia.org/T150328 `DispatchingEntityLookup` should be adjusted. This should happen before releasing a new version of this component.~~

**Comment by manicki** [comment]
`DispatchingEntityLookup` is now ready to be released.

**Comment by manicki** [comment]
Added sentence saying that we raised DM version requirement

**Pull request merged**
