### PR TITLE
Introduce FormatterUrlLookup.

### PR DESCRIPTION
**Pull request by brightbyte**
NOTE: needs a minor release. 

[Bug: T112762](http://phabricator.wikimedia.org/T112762)

### CODE REVIEW

**Comment by thiemowmde** [comment]
We already know we need to lookups for very similar things, one for the URL of an identifier and one for the URI. Should these two be in the same interface? Two methods? One method with a parameter? Isn't a generic "check if property P1 does have a statement with property P2 and return it's value" lookup better?

**Comment by brightbyte** [comment]
I'm inclined to add the method for getting the URI pattern to the same interface.
A generic interface that takes a PropertyID means that the caller has to somehow know the right property ID (we'd have to inject config variables). It's also unclear what the lookup should do if the requested property isn't configured to be recorded in the property_info table.

**Comment by JeroenDeDauw** [comment]
Where do you intend to use this interface? And why put it in this component? (-1 until answered, not saying there is an issue before though.)

**Comment by thiemowmde** [comment]
I'm also curious why this interface needs to be in this component. It seems to be very specific for a use case that no other user of this component may have. Can't this live in WikibaseRepo?

**Comment by brightbyte** [comment]
The interface is here because it is needed by both Client and Repo. I could also put it into Lib, if you prefer. It's used here: https://gerrit.wikimedia.org/r/#/c/254161/

The interface is specific for providing URL patterns associated with properties. Any client that wants to generate URLs for external IDs will need this (unless we generate Snaks with derived values attached directly from the JSON the client gets from the API - but even that would only work for clients that use the web API, not for client wikis).

**Comment by JeroenDeDauw** [comment]
> It's used here: https://gerrit.wikimedia.org/r/#/c/254161/

That does not answer my question actually. Implementing an interface is not really making use of it. Where will we have something of the type defined by this interface?

**Comment by JeroenDeDauw** [comment]
> The interface is here because it is needed by both Client and Repo.

Right. Thanks for considering that. With the info I have so far I think it's a better tradeoff to keep it in Lib with the classes implementing it. That is more cohesive and keeps the "formatter URL pattern" concept out of this component.

**Comment by thiemowmde** [comment]
I agree with Jeroen, see my comments in https://gerrit.wikimedia.org/r/254161.

**Comment by brightbyte** [comment]
Ok, I'll move this into Lib. I was following the example of PropertyDataTypeLookup. Do you think that would also better be in Lib?

In any case, we should move the formatters  into their own component. And the service implementation they use also need a new component, since most of them depend on MediaWiki.

**Comment by JeroenDeDauw** [comment]
> I was following the example of PropertyDataTypeLookup. Do you think that would also better be in Lib?

No - it has implementations in this component, is used outside of Wikibase.git and does not introduce new concepts to this component.

**Pull request closed without merging**
