### PR TITLE
Make use of DataModel 6.1 features

### PR DESCRIPTION
**Pull request by thiemowmde**
~~Please do not merge to early. Wait for other reasons to have a breaking 4.0 release please.~~

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Breaking how?

**Comment by thiemowmde** [comment]
Dropping compatibility with older versions is something I always consider some kind of "breaking" change. It's none, you are right.

**Comment by JeroenDeDauw** [comment]
I was not making a point, just asking a question. So I can't be right ;p

**Comment by brightbyte** [comment]
Please rebase

**Comment by thiemowmde** [comment]
Rebased.

**Pull request merged**
