### PR TITLE
Fixed uncaught exception in EntityIdLabelFormatter::formatEntityId

### PR DESCRIPTION
**Pull request by addshore**
https://phabricator.wikimedia.org/T112003

This also adds release notes and prepares
for a new minor release

### CODE REVIEW

**Comment by filbertkm** [comment]
now I get https://phabricator.wikimedia.org/P2003 :(

**Comment by thiemowmde** [comment]
+1?

**Comment by filbertkm** [comment]
i think the other issue is unrelated and https://gerrit.wikimedia.org/r/#/c/237357/1 fixes it

**Comment by filbertkm** [comment]
well, it is related yet a separate issue

**Comment by thiemowmde** [comment]
Do not forget to update ~~the WIKIBASE_DATAMODEL_VERSION constant~~.

**Comment by addshore** [comment]
This component doesn't have a version constant

**Pull request merged**
